package cn.sunline.demo.mapper;
import org.apache.ibatis.session.SqlSessionFactory;
import org.mybatis.spring.SqlSessionFactoryBean;
import javax.sql.DataSource;
import java.io.File;
import java.util.ArrayList;
import java.util.List;import cn.sunline.tiny.core.Constant;
import cn.sunline.tiny.util.FileUtil;
import java.lang.reflect.Method;
import org.springframework.core.io.ByteArrayResource;
import org.springframework.core.io.Resource;
import org.springframework.core.io.support.PathMatchingResourcePatternResolver;

/**
 * mapper Auxiliary class, ide dynamic generation
 */
public class TinyMapper {

	public static SqlSessionFactory getSqlSessionFactoryBean(DataSource dataSource){
		SqlSessionFactoryBean sqlSessionFactoryBean=new SqlSessionFactoryBean();
		try {
			sqlSessionFactoryBean.setDataSource(dataSource);
	        // 设置别名包（实体类）
	        sqlSessionFactoryBean.setTypeAliasesPackage("cn.sunline.demo.entity");
			String path =Constant.getWebPath()+File.separator+"mapper";
	        File mapperFold = new File(path);
	        if(!mapperFold.exists()) {
	        	return null;
	        }
			List<Resource> rs = new ArrayList<Resource>();
	        for(File file : mapperFold.listFiles()) {
	        	String name = file.getName();
	        	if(name.endsWith("xml")) {
	        		String xml = FileUtil.read(file);
	        		
	        		try {
	        			 Method getMapper = TinyMapper.class.getMethod("get"+name.substring(0,name.length()-4));
		        		 String s = (String) getMapper.invoke(null,null);
		        		 //System.out.println(s);
		        		 xml = xml.replace("</mapper>", s)+"</mapper>";
		        		 
	        		}catch(Exception ex) {
	        			
	        			//System.out.println(name+"Can not identify Mapper");
	        			 
	        		}
					ByteArrayResource bs = new ByteArrayResource(xml.getBytes("utf-8"),file.getPath());
	        		rs.add(bs);
	        	}
	        }
	        Resource[] rss = new Resource[rs.size()];
	        for(int i=0;i<rs.size();i++) {
	        	rss[i] = rs.get(i);
	        }
	      
	        //设置sql配置文件路径
	        sqlSessionFactoryBean.setMapperLocations(rss);
	        //-- 加载mybatis的全局配置文件  
	        Resource mybatisConfigXml = new PathMatchingResourcePatternResolver().getResource("classpath:mybatis-config.xml");
	        sqlSessionFactoryBean.setConfigLocation(mybatisConfigXml);			return sqlSessionFactoryBean.getObject();
		} catch (Exception e) {
			e.printStackTrace();
			throw new RuntimeException(e);
		}
	}


	public static String getTCollectionMapper() {

return	"<resultMap id=\"BaseResultMap\" type=\"cn.sunline.demo.entity.TCollection\">"
		+"	<id column=\"id\" jdbcType=\"VARCHAR\" property=\"id\" />"
		+"	<result column=\"create_date\" jdbcType=\"TIMESTAMP\" property=\"createDate\" />"
		+"	<result column=\"modify_date\" jdbcType=\"TIMESTAMP\" property=\"modifyDate\" />"
		+"	<result column=\"collection_id\" jdbcType=\"VARCHAR\" property=\"collectionId\" />"
		+"	<result column=\"good_id\" jdbcType=\"VARCHAR\" property=\"goodId\" />"
		+"	<result column=\"good_name\" jdbcType=\"VARCHAR\" property=\"goodName\" />"
		+"	<result column=\"good_desc\" jdbcType=\"VARCHAR\" property=\"goodDesc\" />"
		+"	<result column=\"good_price\" jdbcType=\"VARCHAR\" property=\"goodPrice\" />"
		+"	<result column=\"good_type\" jdbcType=\"VARCHAR\" property=\"goodType\" />"
		+"	<result column=\"user_id\" jdbcType=\"BIGINT\" property=\"userId\" />"
		+"	<result column=\"del\" jdbcType=\"CHAR\" property=\"del\" />"
	+"	</resultMap>"
	+"	<sql id=\"Base_Column_List\">"
		+"id,create_date,modify_date,collection_id,good_id,good_name,good_desc,good_price,good_type,user_id,del"
	+"	</sql>"
	+"	<select id=\"selectById\" parameterType=\"String\" resultMap=\"BaseResultMap\">"
		+"	select "
		+"	<include refid=\"Base_Column_List\" />"
		+"	from t_collection"
		+"	where id = #{id,jdbcType=VARCHAR}"
	+"	</select>"
	+"	<delete id=\"deleteById\" parameterType=\"String\">"
		+"	delete from t_collection"
		+"	where id = #{id,jdbcType=VARCHAR}"
	+"	</delete>"
	+"	<insert id=\"insert\" keyColumn=\"id\" keyProperty=\"id\" parameterType=\"cn.sunline.demo.entity.TCollection\" useGeneratedKeys=\"true\">"
		+"	insert into t_collection"
		+"	<trim prefix=\"(\" suffix=\")\" suffixOverrides=\",\">"
			+"<if test=\"id != null\">"
				+"id,"
			+"</if>"
			+"<if test=\"createDate != null\">"
				+"create_date,"
			+"</if>"
			+"<if test=\"modifyDate != null\">"
				+"modify_date,"
			+"</if>"
			+"<if test=\"collectionId != null\">"
				+"collection_id,"
			+"</if>"
			+"<if test=\"goodId != null\">"
				+"good_id,"
			+"</if>"
			+"<if test=\"goodName != null\">"
				+"good_name,"
			+"</if>"
			+"<if test=\"goodDesc != null\">"
				+"good_desc,"
			+"</if>"
			+"<if test=\"goodPrice != null\">"
				+"good_price,"
			+"</if>"
			+"<if test=\"goodType != null\">"
				+"good_type,"
			+"</if>"
			+"<if test=\"userId != null\">"
				+"user_id,"
			+"</if>"
			+"<if test=\"del != null\">"
				+"del,"
			+"</if>"
		+"	</trim>"
		+"	<trim prefix=\"values (\" suffix=\")\" suffixOverrides=\",\">"
			+"<if test=\"id != null\">"
				+"#{id,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"createDate != null\">"
				+"#{createDate,jdbcType=TIMESTAMP},"
			+"</if>"
			+"<if test=\"modifyDate != null\">"
				+"#{modifyDate,jdbcType=TIMESTAMP},"
			+"</if>"
			+"<if test=\"collectionId != null\">"
				+"#{collectionId,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"goodId != null\">"
				+"#{goodId,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"goodName != null\">"
				+"#{goodName,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"goodDesc != null\">"
				+"#{goodDesc,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"goodPrice != null\">"
				+"#{goodPrice,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"goodType != null\">"
				+"#{goodType,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"userId != null\">"
				+"#{userId,jdbcType=BIGINT},"
			+"</if>"
			+"<if test=\"del != null\">"
				+"#{del,jdbcType=CHAR},"
			+"</if>"
		+"	</trim>"
	+"	</insert>"
	+"	<update id=\"updateById\" parameterType=\"cn.sunline.demo.entity.TCollection\">"
		+"	update t_collection"
		+"	<set>"
		+"	<if test=\"createDate != null\">"
			+"create_date = #{createDate,jdbcType=TIMESTAMP},"
		+"	</if>"
		+"	<if test=\"modifyDate != null\">"
			+"modify_date = #{modifyDate,jdbcType=TIMESTAMP},"
		+"	</if>"
		+"	<if test=\"collectionId != null\">"
			+"collection_id = #{collectionId,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"goodId != null\">"
			+"good_id = #{goodId,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"goodName != null\">"
			+"good_name = #{goodName,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"goodDesc != null\">"
			+"good_desc = #{goodDesc,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"goodPrice != null\">"
			+"good_price = #{goodPrice,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"goodType != null\">"
			+"good_type = #{goodType,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"userId != null\">"
			+"user_id = #{userId,jdbcType=BIGINT},"
		+"	</if>"
		+"	<if test=\"del != null\">"
			+"del = #{del,jdbcType=CHAR},"
		+"	</if>"
		+"	</set>"
		+"	where id = #{id,jdbcType=VARCHAR}"
	+"	</update>";
	}
	public static String getTGoodAttributesMapper() {

return	"<resultMap id=\"BaseResultMap\" type=\"cn.sunline.demo.entity.TGoodAttributes\">"
		+"	<id column=\"id\" jdbcType=\"VARCHAR\" property=\"id\" />"
		+"	<result column=\"create_date\" jdbcType=\"TIMESTAMP\" property=\"createDate\" />"
		+"	<result column=\"modify_date\" jdbcType=\"TIMESTAMP\" property=\"modifyDate\" />"
		+"	<result column=\"good_id\" jdbcType=\"VARCHAR\" property=\"goodId\" />"
		+"	<result column=\"attributes_sort\" jdbcType=\"CLOB\" property=\"attributesSort\" />"
		+"	<result column=\"good_color\" jdbcType=\"CLOB\" property=\"goodColor\" />"
		+"	<result column=\"good_capacity\" jdbcType=\"CLOB\" property=\"goodCapacity\" />"
		+"	<result column=\"good_size\" jdbcType=\"CLOB\" property=\"goodSize\" />"
		+"	<result column=\"attributes_pic\" jdbcType=\"VARCHAR\" property=\"attributesPic\" />"
		+"	<result column=\"good_param\" jdbcType=\"CLOB\" property=\"goodParam\" />"
		+"	<result column=\"del\" jdbcType=\"CHAR\" property=\"del\" />"
	+"	</resultMap>"
	+"	<sql id=\"Base_Column_List\">"
		+"id,create_date,modify_date,good_id,attributes_sort,good_color,good_capacity,good_size,attributes_pic,good_param,del"
	+"	</sql>"
	+"	<select id=\"selectById\" parameterType=\"String\" resultMap=\"BaseResultMap\">"
		+"	select "
		+"	<include refid=\"Base_Column_List\" />"
		+"	from t_good_attributes"
		+"	where id = #{id,jdbcType=VARCHAR}"
	+"	</select>"
	+"	<delete id=\"deleteById\" parameterType=\"String\">"
		+"	delete from t_good_attributes"
		+"	where id = #{id,jdbcType=VARCHAR}"
	+"	</delete>"
	+"	<insert id=\"insert\" keyColumn=\"id\" keyProperty=\"id\" parameterType=\"cn.sunline.demo.entity.TGoodAttributes\" useGeneratedKeys=\"true\">"
		+"	insert into t_good_attributes"
		+"	<trim prefix=\"(\" suffix=\")\" suffixOverrides=\",\">"
			+"<if test=\"id != null\">"
				+"id,"
			+"</if>"
			+"<if test=\"createDate != null\">"
				+"create_date,"
			+"</if>"
			+"<if test=\"modifyDate != null\">"
				+"modify_date,"
			+"</if>"
			+"<if test=\"goodId != null\">"
				+"good_id,"
			+"</if>"
			+"<if test=\"attributesSort != null\">"
				+"attributes_sort,"
			+"</if>"
			+"<if test=\"goodColor != null\">"
				+"good_color,"
			+"</if>"
			+"<if test=\"goodCapacity != null\">"
				+"good_capacity,"
			+"</if>"
			+"<if test=\"goodSize != null\">"
				+"good_size,"
			+"</if>"
			+"<if test=\"attributesPic != null\">"
				+"attributes_pic,"
			+"</if>"
			+"<if test=\"goodParam != null\">"
				+"good_param,"
			+"</if>"
			+"<if test=\"del != null\">"
				+"del,"
			+"</if>"
		+"	</trim>"
		+"	<trim prefix=\"values (\" suffix=\")\" suffixOverrides=\",\">"
			+"<if test=\"id != null\">"
				+"#{id,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"createDate != null\">"
				+"#{createDate,jdbcType=TIMESTAMP},"
			+"</if>"
			+"<if test=\"modifyDate != null\">"
				+"#{modifyDate,jdbcType=TIMESTAMP},"
			+"</if>"
			+"<if test=\"goodId != null\">"
				+"#{goodId,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"attributesSort != null\">"
				+"#{attributesSort,jdbcType=CLOB},"
			+"</if>"
			+"<if test=\"goodColor != null\">"
				+"#{goodColor,jdbcType=CLOB},"
			+"</if>"
			+"<if test=\"goodCapacity != null\">"
				+"#{goodCapacity,jdbcType=CLOB},"
			+"</if>"
			+"<if test=\"goodSize != null\">"
				+"#{goodSize,jdbcType=CLOB},"
			+"</if>"
			+"<if test=\"attributesPic != null\">"
				+"#{attributesPic,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"goodParam != null\">"
				+"#{goodParam,jdbcType=CLOB},"
			+"</if>"
			+"<if test=\"del != null\">"
				+"#{del,jdbcType=CHAR},"
			+"</if>"
		+"	</trim>"
	+"	</insert>"
	+"	<update id=\"updateById\" parameterType=\"cn.sunline.demo.entity.TGoodAttributes\">"
		+"	update t_good_attributes"
		+"	<set>"
		+"	<if test=\"createDate != null\">"
			+"create_date = #{createDate,jdbcType=TIMESTAMP},"
		+"	</if>"
		+"	<if test=\"modifyDate != null\">"
			+"modify_date = #{modifyDate,jdbcType=TIMESTAMP},"
		+"	</if>"
		+"	<if test=\"goodId != null\">"
			+"good_id = #{goodId,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"attributesSort != null\">"
			+"attributes_sort = #{attributesSort,jdbcType=CLOB},"
		+"	</if>"
		+"	<if test=\"goodColor != null\">"
			+"good_color = #{goodColor,jdbcType=CLOB},"
		+"	</if>"
		+"	<if test=\"goodCapacity != null\">"
			+"good_capacity = #{goodCapacity,jdbcType=CLOB},"
		+"	</if>"
		+"	<if test=\"goodSize != null\">"
			+"good_size = #{goodSize,jdbcType=CLOB},"
		+"	</if>"
		+"	<if test=\"attributesPic != null\">"
			+"attributes_pic = #{attributesPic,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"goodParam != null\">"
			+"good_param = #{goodParam,jdbcType=CLOB},"
		+"	</if>"
		+"	<if test=\"del != null\">"
			+"del = #{del,jdbcType=CHAR},"
		+"	</if>"
		+"	</set>"
		+"	where id = #{id,jdbcType=VARCHAR}"
	+"	</update>";
	}
	public static String getTGoodImageMapper() {

return	"<resultMap id=\"BaseResultMap\" type=\"cn.sunline.demo.entity.TGoodImage\">"
		+"	<id column=\"id\" jdbcType=\"VARCHAR\" property=\"id\" />"
		+"	<result column=\"create_date\" jdbcType=\"TIMESTAMP\" property=\"createDate\" />"
		+"	<result column=\"modify_date\" jdbcType=\"TIMESTAMP\" property=\"modifyDate\" />"
		+"	<result column=\"image_id\" jdbcType=\"VARCHAR\" property=\"imageId\" />"
		+"	<result column=\"Image_url\" jdbcType=\"VARCHAR\" property=\"imageUrl\" />"
		+"	<result column=\"good_id\" jdbcType=\"VARCHAR\" property=\"goodId\" />"
		+"	<result column=\"del\" jdbcType=\"CHAR\" property=\"del\" />"
	+"	</resultMap>"
	+"	<sql id=\"Base_Column_List\">"
		+"id,create_date,modify_date,image_id,Image_url,good_id,del"
	+"	</sql>"
	+"	<select id=\"selectById\" parameterType=\"String\" resultMap=\"BaseResultMap\">"
		+"	select "
		+"	<include refid=\"Base_Column_List\" />"
		+"	from t_good_image"
		+"	where id = #{id,jdbcType=VARCHAR}"
	+"	</select>"
	+"	<delete id=\"deleteById\" parameterType=\"String\">"
		+"	delete from t_good_image"
		+"	where id = #{id,jdbcType=VARCHAR}"
	+"	</delete>"
	+"	<insert id=\"insert\" keyColumn=\"id\" keyProperty=\"id\" parameterType=\"cn.sunline.demo.entity.TGoodImage\" useGeneratedKeys=\"true\">"
		+"	insert into t_good_image"
		+"	<trim prefix=\"(\" suffix=\")\" suffixOverrides=\",\">"
			+"<if test=\"id != null\">"
				+"id,"
			+"</if>"
			+"<if test=\"createDate != null\">"
				+"create_date,"
			+"</if>"
			+"<if test=\"modifyDate != null\">"
				+"modify_date,"
			+"</if>"
			+"<if test=\"imageId != null\">"
				+"image_id,"
			+"</if>"
			+"<if test=\"imageUrl != null\">"
				+"Image_url,"
			+"</if>"
			+"<if test=\"goodId != null\">"
				+"good_id,"
			+"</if>"
			+"<if test=\"del != null\">"
				+"del,"
			+"</if>"
		+"	</trim>"
		+"	<trim prefix=\"values (\" suffix=\")\" suffixOverrides=\",\">"
			+"<if test=\"id != null\">"
				+"#{id,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"createDate != null\">"
				+"#{createDate,jdbcType=TIMESTAMP},"
			+"</if>"
			+"<if test=\"modifyDate != null\">"
				+"#{modifyDate,jdbcType=TIMESTAMP},"
			+"</if>"
			+"<if test=\"imageId != null\">"
				+"#{imageId,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"imageUrl != null\">"
				+"#{imageUrl,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"goodId != null\">"
				+"#{goodId,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"del != null\">"
				+"#{del,jdbcType=CHAR},"
			+"</if>"
		+"	</trim>"
	+"	</insert>"
	+"	<update id=\"updateById\" parameterType=\"cn.sunline.demo.entity.TGoodImage\">"
		+"	update t_good_image"
		+"	<set>"
		+"	<if test=\"createDate != null\">"
			+"create_date = #{createDate,jdbcType=TIMESTAMP},"
		+"	</if>"
		+"	<if test=\"modifyDate != null\">"
			+"modify_date = #{modifyDate,jdbcType=TIMESTAMP},"
		+"	</if>"
		+"	<if test=\"imageId != null\">"
			+"image_id = #{imageId,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"imageUrl != null\">"
			+"Image_url = #{imageUrl,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"goodId != null\">"
			+"good_id = #{goodId,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"del != null\">"
			+"del = #{del,jdbcType=CHAR},"
		+"	</if>"
		+"	</set>"
		+"	where id = #{id,jdbcType=VARCHAR}"
	+"	</update>";
	}
	public static String getTGoodPromotionMapper() {

return	"<resultMap id=\"BaseResultMap\" type=\"cn.sunline.demo.entity.TGoodPromotion\">"
		+"	<id column=\"id\" jdbcType=\"VARCHAR\" property=\"id\" />"
		+"	<result column=\"create_date\" jdbcType=\"TIMESTAMP\" property=\"createDate\" />"
		+"	<result column=\"modify_date\" jdbcType=\"TIMESTAMP\" property=\"modifyDate\" />"
		+"	<result column=\"good_id\" jdbcType=\"VARCHAR\" property=\"goodId\" />"
		+"	<result column=\"gift_point\" jdbcType=\"VARCHAR\" property=\"giftPoint\" />"
		+"	<result column=\"gift_growth_value\" jdbcType=\"VARCHAR\" property=\"giftGrowthValue\" />"
		+"	<result column=\"service_guarantee\" jdbcType=\"CLOB\" property=\"serviceGuarantee\" />"
		+"	<result column=\"detailed_page_title\" jdbcType=\"VARCHAR\" property=\"detailedPageTitle\" />"
		+"	<result column=\"detailed_page_desc\" jdbcType=\"VARCHAR\" property=\"detailedPageDesc\" />"
		+"	<result column=\"good_keywords\" jdbcType=\"VARCHAR\" property=\"goodKeywords\" />"
		+"	<result column=\"good_note\" jdbcType=\"VARCHAR\" property=\"goodNote\" />"
		+"	<result column=\"select_offer_method\" jdbcType=\"CLOB\" property=\"selectOfferMethod\" />"
		+"	<result column=\"del\" jdbcType=\"CHAR\" property=\"del\" />"
	+"	</resultMap>"
	+"	<sql id=\"Base_Column_List\">"
		+"id,create_date,modify_date,good_id,gift_point,gift_growth_value,service_guarantee,detailed_page_title,detailed_page_desc,good_keywords,good_note,select_offer_method,del"
	+"	</sql>"
	+"	<select id=\"selectById\" parameterType=\"String\" resultMap=\"BaseResultMap\">"
		+"	select "
		+"	<include refid=\"Base_Column_List\" />"
		+"	from t_good_promotion"
		+"	where id = #{id,jdbcType=VARCHAR}"
	+"	</select>"
	+"	<delete id=\"deleteById\" parameterType=\"String\">"
		+"	delete from t_good_promotion"
		+"	where id = #{id,jdbcType=VARCHAR}"
	+"	</delete>"
	+"	<insert id=\"insert\" keyColumn=\"id\" keyProperty=\"id\" parameterType=\"cn.sunline.demo.entity.TGoodPromotion\" useGeneratedKeys=\"true\">"
		+"	insert into t_good_promotion"
		+"	<trim prefix=\"(\" suffix=\")\" suffixOverrides=\",\">"
			+"<if test=\"id != null\">"
				+"id,"
			+"</if>"
			+"<if test=\"createDate != null\">"
				+"create_date,"
			+"</if>"
			+"<if test=\"modifyDate != null\">"
				+"modify_date,"
			+"</if>"
			+"<if test=\"goodId != null\">"
				+"good_id,"
			+"</if>"
			+"<if test=\"giftPoint != null\">"
				+"gift_point,"
			+"</if>"
			+"<if test=\"giftGrowthValue != null\">"
				+"gift_growth_value,"
			+"</if>"
			+"<if test=\"serviceGuarantee != null\">"
				+"service_guarantee,"
			+"</if>"
			+"<if test=\"detailedPageTitle != null\">"
				+"detailed_page_title,"
			+"</if>"
			+"<if test=\"detailedPageDesc != null\">"
				+"detailed_page_desc,"
			+"</if>"
			+"<if test=\"goodKeywords != null\">"
				+"good_keywords,"
			+"</if>"
			+"<if test=\"goodNote != null\">"
				+"good_note,"
			+"</if>"
			+"<if test=\"selectOfferMethod != null\">"
				+"select_offer_method,"
			+"</if>"
			+"<if test=\"del != null\">"
				+"del,"
			+"</if>"
		+"	</trim>"
		+"	<trim prefix=\"values (\" suffix=\")\" suffixOverrides=\",\">"
			+"<if test=\"id != null\">"
				+"#{id,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"createDate != null\">"
				+"#{createDate,jdbcType=TIMESTAMP},"
			+"</if>"
			+"<if test=\"modifyDate != null\">"
				+"#{modifyDate,jdbcType=TIMESTAMP},"
			+"</if>"
			+"<if test=\"goodId != null\">"
				+"#{goodId,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"giftPoint != null\">"
				+"#{giftPoint,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"giftGrowthValue != null\">"
				+"#{giftGrowthValue,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"serviceGuarantee != null\">"
				+"#{serviceGuarantee,jdbcType=CLOB},"
			+"</if>"
			+"<if test=\"detailedPageTitle != null\">"
				+"#{detailedPageTitle,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"detailedPageDesc != null\">"
				+"#{detailedPageDesc,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"goodKeywords != null\">"
				+"#{goodKeywords,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"goodNote != null\">"
				+"#{goodNote,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"selectOfferMethod != null\">"
				+"#{selectOfferMethod,jdbcType=CLOB},"
			+"</if>"
			+"<if test=\"del != null\">"
				+"#{del,jdbcType=CHAR},"
			+"</if>"
		+"	</trim>"
	+"	</insert>"
	+"	<update id=\"updateById\" parameterType=\"cn.sunline.demo.entity.TGoodPromotion\">"
		+"	update t_good_promotion"
		+"	<set>"
		+"	<if test=\"createDate != null\">"
			+"create_date = #{createDate,jdbcType=TIMESTAMP},"
		+"	</if>"
		+"	<if test=\"modifyDate != null\">"
			+"modify_date = #{modifyDate,jdbcType=TIMESTAMP},"
		+"	</if>"
		+"	<if test=\"goodId != null\">"
			+"good_id = #{goodId,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"giftPoint != null\">"
			+"gift_point = #{giftPoint,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"giftGrowthValue != null\">"
			+"gift_growth_value = #{giftGrowthValue,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"serviceGuarantee != null\">"
			+"service_guarantee = #{serviceGuarantee,jdbcType=CLOB},"
		+"	</if>"
		+"	<if test=\"detailedPageTitle != null\">"
			+"detailed_page_title = #{detailedPageTitle,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"detailedPageDesc != null\">"
			+"detailed_page_desc = #{detailedPageDesc,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"goodKeywords != null\">"
			+"good_keywords = #{goodKeywords,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"goodNote != null\">"
			+"good_note = #{goodNote,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"selectOfferMethod != null\">"
			+"select_offer_method = #{selectOfferMethod,jdbcType=CLOB},"
		+"	</if>"
		+"	<if test=\"del != null\">"
			+"del = #{del,jdbcType=CHAR},"
		+"	</if>"
		+"	</set>"
		+"	where id = #{id,jdbcType=VARCHAR}"
	+"	</update>";
	}
	public static String getTGoodsMapper() {

return	"<resultMap id=\"BaseResultMap\" type=\"cn.sunline.demo.entity.TGoods\">"
		+"	<id column=\"id\" jdbcType=\"VARCHAR\" property=\"id\" />"
		+"	<result column=\"create_date\" jdbcType=\"TIMESTAMP\" property=\"createDate\" />"
		+"	<result column=\"modify_date\" jdbcType=\"TIMESTAMP\" property=\"modifyDate\" />"
		+"	<result column=\"good_id\" jdbcType=\"VARCHAR\" property=\"goodId\" />"
		+"	<result column=\"good_name\" jdbcType=\"VARCHAR\" property=\"goodName\" />"
		+"	<result column=\"good_desc\" jdbcType=\"VARCHAR\" property=\"goodDesc\" />"
		+"	<result column=\"good_price\" jdbcType=\"VARCHAR\" property=\"goodPrice\" />"
		+"	<result column=\"good_type\" jdbcType=\"VARCHAR\" property=\"goodType\" />"
		+"	<result column=\"del\" jdbcType=\"CHAR\" property=\"del\" />"
		+"	<result column=\"good_stock\" jdbcType=\"VARCHAR\" property=\"goodStock\" />"
		+"	<result column=\"original_price\" jdbcType=\"VARCHAR\" property=\"originalPrice\" />"
	+"	</resultMap>"
	+"	<sql id=\"Base_Column_List\">"
		+"id,create_date,modify_date,good_id,good_name,good_desc,good_price,good_type,del,good_stock,original_price"
	+"	</sql>"
	+"	<select id=\"selectById\" parameterType=\"String\" resultMap=\"BaseResultMap\">"
		+"	select "
		+"	<include refid=\"Base_Column_List\" />"
		+"	from t_goods"
		+"	where id = #{id,jdbcType=VARCHAR}"
	+"	</select>"
	+"	<delete id=\"deleteById\" parameterType=\"String\">"
		+"	delete from t_goods"
		+"	where id = #{id,jdbcType=VARCHAR}"
	+"	</delete>"
	+"	<insert id=\"insert\" keyColumn=\"id\" keyProperty=\"id\" parameterType=\"cn.sunline.demo.entity.TGoods\" useGeneratedKeys=\"true\">"
		+"	insert into t_goods"
		+"	<trim prefix=\"(\" suffix=\")\" suffixOverrides=\",\">"
			+"<if test=\"id != null\">"
				+"id,"
			+"</if>"
			+"<if test=\"createDate != null\">"
				+"create_date,"
			+"</if>"
			+"<if test=\"modifyDate != null\">"
				+"modify_date,"
			+"</if>"
			+"<if test=\"goodId != null\">"
				+"good_id,"
			+"</if>"
			+"<if test=\"goodName != null\">"
				+"good_name,"
			+"</if>"
			+"<if test=\"goodDesc != null\">"
				+"good_desc,"
			+"</if>"
			+"<if test=\"goodPrice != null\">"
				+"good_price,"
			+"</if>"
			+"<if test=\"goodType != null\">"
				+"good_type,"
			+"</if>"
			+"<if test=\"del != null\">"
				+"del,"
			+"</if>"
			+"<if test=\"goodStock != null\">"
				+"good_stock,"
			+"</if>"
			+"<if test=\"originalPrice != null\">"
				+"original_price,"
			+"</if>"
		+"	</trim>"
		+"	<trim prefix=\"values (\" suffix=\")\" suffixOverrides=\",\">"
			+"<if test=\"id != null\">"
				+"#{id,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"createDate != null\">"
				+"#{createDate,jdbcType=TIMESTAMP},"
			+"</if>"
			+"<if test=\"modifyDate != null\">"
				+"#{modifyDate,jdbcType=TIMESTAMP},"
			+"</if>"
			+"<if test=\"goodId != null\">"
				+"#{goodId,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"goodName != null\">"
				+"#{goodName,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"goodDesc != null\">"
				+"#{goodDesc,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"goodPrice != null\">"
				+"#{goodPrice,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"goodType != null\">"
				+"#{goodType,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"del != null\">"
				+"#{del,jdbcType=CHAR},"
			+"</if>"
			+"<if test=\"goodStock != null\">"
				+"#{goodStock,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"originalPrice != null\">"
				+"#{originalPrice,jdbcType=VARCHAR},"
			+"</if>"
		+"	</trim>"
	+"	</insert>"
	+"	<update id=\"updateById\" parameterType=\"cn.sunline.demo.entity.TGoods\">"
		+"	update t_goods"
		+"	<set>"
		+"	<if test=\"createDate != null\">"
			+"create_date = #{createDate,jdbcType=TIMESTAMP},"
		+"	</if>"
		+"	<if test=\"modifyDate != null\">"
			+"modify_date = #{modifyDate,jdbcType=TIMESTAMP},"
		+"	</if>"
		+"	<if test=\"goodId != null\">"
			+"good_id = #{goodId,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"goodName != null\">"
			+"good_name = #{goodName,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"goodDesc != null\">"
			+"good_desc = #{goodDesc,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"goodPrice != null\">"
			+"good_price = #{goodPrice,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"goodType != null\">"
			+"good_type = #{goodType,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"del != null\">"
			+"del = #{del,jdbcType=CHAR},"
		+"	</if>"
		+"	<if test=\"goodStock != null\">"
			+"good_stock = #{goodStock,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"originalPrice != null\">"
			+"original_price = #{originalPrice,jdbcType=VARCHAR},"
		+"	</if>"
		+"	</set>"
		+"	where id = #{id,jdbcType=VARCHAR}"
	+"	</update>";
	}
	public static String getTGoodsDetailMapper() {

return	"<resultMap id=\"BaseResultMap\" type=\"cn.sunline.demo.entity.TGoodsDetail\">"
		+"	<id column=\"id\" jdbcType=\"VARCHAR\" property=\"id\" />"
		+"	<result column=\"create_date\" jdbcType=\"TIMESTAMP\" property=\"createDate\" />"
		+"	<result column=\"modify_date\" jdbcType=\"TIMESTAMP\" property=\"modifyDate\" />"
		+"	<result column=\"good_id\" jdbcType=\"VARCHAR\" property=\"goodId\" />"
		+"	<result column=\"item_number\" jdbcType=\"VARCHAR\" property=\"itemNumber\" />"
		+"	<result column=\"whether_shelf\" jdbcType=\"CHAR\" property=\"whetherShelf\" />"
		+"	<result column=\"whether_new\" jdbcType=\"CHAR\" property=\"whetherNew\" />"
		+"	<result column=\"whether_recommend\" jdbcType=\"CHAR\" property=\"whetherRecommend\" />"
		+"	<result column=\"good_sort\" jdbcType=\"VARCHAR\" property=\"goodSort\" />"
		+"	<result column=\"sales_volume\" jdbcType=\"VARCHAR\" property=\"salesVolume\" />"
		+"	<result column=\"approval_status\" jdbcType=\"CHAR\" property=\"approvalStatus\" />"
		+"	<result column=\"subtitle\" jdbcType=\"VARCHAR\" property=\"subtitle\" />"
		+"	<result column=\"good_weight\" jdbcType=\"VARCHAR\" property=\"goodWeight\" />"
		+"	<result column=\"del\" jdbcType=\"CHAR\" property=\"del\" />"
	+"	</resultMap>"
	+"	<sql id=\"Base_Column_List\">"
		+"id,create_date,modify_date,good_id,item_number,whether_shelf,whether_new,whether_recommend,good_sort,sales_volume,approval_status,subtitle,good_weight,del"
	+"	</sql>"
	+"	<select id=\"selectById\" parameterType=\"String\" resultMap=\"BaseResultMap\">"
		+"	select "
		+"	<include refid=\"Base_Column_List\" />"
		+"	from t_goods_detail"
		+"	where id = #{id,jdbcType=VARCHAR}"
	+"	</select>"
	+"	<delete id=\"deleteById\" parameterType=\"String\">"
		+"	delete from t_goods_detail"
		+"	where id = #{id,jdbcType=VARCHAR}"
	+"	</delete>"
	+"	<insert id=\"insert\" keyColumn=\"id\" keyProperty=\"id\" parameterType=\"cn.sunline.demo.entity.TGoodsDetail\" useGeneratedKeys=\"true\">"
		+"	insert into t_goods_detail"
		+"	<trim prefix=\"(\" suffix=\")\" suffixOverrides=\",\">"
			+"<if test=\"id != null\">"
				+"id,"
			+"</if>"
			+"<if test=\"createDate != null\">"
				+"create_date,"
			+"</if>"
			+"<if test=\"modifyDate != null\">"
				+"modify_date,"
			+"</if>"
			+"<if test=\"goodId != null\">"
				+"good_id,"
			+"</if>"
			+"<if test=\"itemNumber != null\">"
				+"item_number,"
			+"</if>"
			+"<if test=\"whetherShelf != null\">"
				+"whether_shelf,"
			+"</if>"
			+"<if test=\"whetherNew != null\">"
				+"whether_new,"
			+"</if>"
			+"<if test=\"whetherRecommend != null\">"
				+"whether_recommend,"
			+"</if>"
			+"<if test=\"goodSort != null\">"
				+"good_sort,"
			+"</if>"
			+"<if test=\"salesVolume != null\">"
				+"sales_volume,"
			+"</if>"
			+"<if test=\"approvalStatus != null\">"
				+"approval_status,"
			+"</if>"
			+"<if test=\"subtitle != null\">"
				+"subtitle,"
			+"</if>"
			+"<if test=\"goodWeight != null\">"
				+"good_weight,"
			+"</if>"
			+"<if test=\"del != null\">"
				+"del,"
			+"</if>"
		+"	</trim>"
		+"	<trim prefix=\"values (\" suffix=\")\" suffixOverrides=\",\">"
			+"<if test=\"id != null\">"
				+"#{id,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"createDate != null\">"
				+"#{createDate,jdbcType=TIMESTAMP},"
			+"</if>"
			+"<if test=\"modifyDate != null\">"
				+"#{modifyDate,jdbcType=TIMESTAMP},"
			+"</if>"
			+"<if test=\"goodId != null\">"
				+"#{goodId,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"itemNumber != null\">"
				+"#{itemNumber,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"whetherShelf != null\">"
				+"#{whetherShelf,jdbcType=CHAR},"
			+"</if>"
			+"<if test=\"whetherNew != null\">"
				+"#{whetherNew,jdbcType=CHAR},"
			+"</if>"
			+"<if test=\"whetherRecommend != null\">"
				+"#{whetherRecommend,jdbcType=CHAR},"
			+"</if>"
			+"<if test=\"goodSort != null\">"
				+"#{goodSort,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"salesVolume != null\">"
				+"#{salesVolume,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"approvalStatus != null\">"
				+"#{approvalStatus,jdbcType=CHAR},"
			+"</if>"
			+"<if test=\"subtitle != null\">"
				+"#{subtitle,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"goodWeight != null\">"
				+"#{goodWeight,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"del != null\">"
				+"#{del,jdbcType=CHAR},"
			+"</if>"
		+"	</trim>"
	+"	</insert>"
	+"	<update id=\"updateById\" parameterType=\"cn.sunline.demo.entity.TGoodsDetail\">"
		+"	update t_goods_detail"
		+"	<set>"
		+"	<if test=\"createDate != null\">"
			+"create_date = #{createDate,jdbcType=TIMESTAMP},"
		+"	</if>"
		+"	<if test=\"modifyDate != null\">"
			+"modify_date = #{modifyDate,jdbcType=TIMESTAMP},"
		+"	</if>"
		+"	<if test=\"goodId != null\">"
			+"good_id = #{goodId,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"itemNumber != null\">"
			+"item_number = #{itemNumber,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"whetherShelf != null\">"
			+"whether_shelf = #{whetherShelf,jdbcType=CHAR},"
		+"	</if>"
		+"	<if test=\"whetherNew != null\">"
			+"whether_new = #{whetherNew,jdbcType=CHAR},"
		+"	</if>"
		+"	<if test=\"whetherRecommend != null\">"
			+"whether_recommend = #{whetherRecommend,jdbcType=CHAR},"
		+"	</if>"
		+"	<if test=\"goodSort != null\">"
			+"good_sort = #{goodSort,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"salesVolume != null\">"
			+"sales_volume = #{salesVolume,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"approvalStatus != null\">"
			+"approval_status = #{approvalStatus,jdbcType=CHAR},"
		+"	</if>"
		+"	<if test=\"subtitle != null\">"
			+"subtitle = #{subtitle,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"goodWeight != null\">"
			+"good_weight = #{goodWeight,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"del != null\">"
			+"del = #{del,jdbcType=CHAR},"
		+"	</if>"
		+"	</set>"
		+"	where id = #{id,jdbcType=VARCHAR}"
	+"	</update>";
	}
	public static String getTGoodsTypeMapper() {

return	"<resultMap id=\"BaseResultMap\" type=\"cn.sunline.demo.entity.TGoodsType\">"
		+"	<id column=\"id\" jdbcType=\"VARCHAR\" property=\"id\" />"
		+"	<result column=\"create_date\" jdbcType=\"TIMESTAMP\" property=\"createDate\" />"
		+"	<result column=\"modify_date\" jdbcType=\"TIMESTAMP\" property=\"modifyDate\" />"
		+"	<result column=\"type_id\" jdbcType=\"VARCHAR\" property=\"typeId\" />"
		+"	<result column=\"type_name\" jdbcType=\"VARCHAR\" property=\"typeName\" />"
		+"	<result column=\"type_par_id\" jdbcType=\"VARCHAR\" property=\"typeParId\" />"
		+"	<result column=\"del\" jdbcType=\"CHAR\" property=\"del\" />"
	+"	</resultMap>"
	+"	<sql id=\"Base_Column_List\">"
		+"id,create_date,modify_date,type_id,type_name,type_par_id,del"
	+"	</sql>"
	+"	<select id=\"selectById\" parameterType=\"String\" resultMap=\"BaseResultMap\">"
		+"	select "
		+"	<include refid=\"Base_Column_List\" />"
		+"	from t_goods_type"
		+"	where id = #{id,jdbcType=VARCHAR}"
	+"	</select>"
	+"	<delete id=\"deleteById\" parameterType=\"String\">"
		+"	delete from t_goods_type"
		+"	where id = #{id,jdbcType=VARCHAR}"
	+"	</delete>"
	+"	<insert id=\"insert\" keyColumn=\"id\" keyProperty=\"id\" parameterType=\"cn.sunline.demo.entity.TGoodsType\" useGeneratedKeys=\"true\">"
		+"	insert into t_goods_type"
		+"	<trim prefix=\"(\" suffix=\")\" suffixOverrides=\",\">"
			+"<if test=\"id != null\">"
				+"id,"
			+"</if>"
			+"<if test=\"createDate != null\">"
				+"create_date,"
			+"</if>"
			+"<if test=\"modifyDate != null\">"
				+"modify_date,"
			+"</if>"
			+"<if test=\"typeId != null\">"
				+"type_id,"
			+"</if>"
			+"<if test=\"typeName != null\">"
				+"type_name,"
			+"</if>"
			+"<if test=\"typeParId != null\">"
				+"type_par_id,"
			+"</if>"
			+"<if test=\"del != null\">"
				+"del,"
			+"</if>"
		+"	</trim>"
		+"	<trim prefix=\"values (\" suffix=\")\" suffixOverrides=\",\">"
			+"<if test=\"id != null\">"
				+"#{id,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"createDate != null\">"
				+"#{createDate,jdbcType=TIMESTAMP},"
			+"</if>"
			+"<if test=\"modifyDate != null\">"
				+"#{modifyDate,jdbcType=TIMESTAMP},"
			+"</if>"
			+"<if test=\"typeId != null\">"
				+"#{typeId,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"typeName != null\">"
				+"#{typeName,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"typeParId != null\">"
				+"#{typeParId,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"del != null\">"
				+"#{del,jdbcType=CHAR},"
			+"</if>"
		+"	</trim>"
	+"	</insert>"
	+"	<update id=\"updateById\" parameterType=\"cn.sunline.demo.entity.TGoodsType\">"
		+"	update t_goods_type"
		+"	<set>"
		+"	<if test=\"createDate != null\">"
			+"create_date = #{createDate,jdbcType=TIMESTAMP},"
		+"	</if>"
		+"	<if test=\"modifyDate != null\">"
			+"modify_date = #{modifyDate,jdbcType=TIMESTAMP},"
		+"	</if>"
		+"	<if test=\"typeId != null\">"
			+"type_id = #{typeId,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"typeName != null\">"
			+"type_name = #{typeName,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"typeParId != null\">"
			+"type_par_id = #{typeParId,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"del != null\">"
			+"del = #{del,jdbcType=CHAR},"
		+"	</if>"
		+"	</set>"
		+"	where id = #{id,jdbcType=VARCHAR}"
	+"	</update>";
	}
	public static String getTGoodsTypeDetailMapper() {

return	"<resultMap id=\"BaseResultMap\" type=\"cn.sunline.demo.entity.TGoodsTypeDetail\">"
		+"	<id column=\"id\" jdbcType=\"VARCHAR\" property=\"id\" />"
		+"	<result column=\"create_date\" jdbcType=\"TIMESTAMP\" property=\"createDate\" />"
		+"	<result column=\"modify_date\" jdbcType=\"TIMESTAMP\" property=\"modifyDate\" />"
		+"	<result column=\"type_id\" jdbcType=\"VARCHAR\" property=\"typeId\" />"
		+"	<result column=\"quantity_unit\" jdbcType=\"VARCHAR\" property=\"quantityUnit\" />"
		+"	<result column=\"navigation_Bar\" jdbcType=\"CHAR\" property=\"navigationBar\" />"
		+"	<result column=\"is_show\" jdbcType=\"CHAR\" property=\"isShow\" />"
		+"	<result column=\"sort_manage\" jdbcType=\"VARCHAR\" property=\"sortManage\" />"
		+"	<result column=\"goods_num\" jdbcType=\"VARCHAR\" property=\"goodsNum\" />"
		+"	<result column=\"cate_image\" jdbcType=\"VARCHAR\" property=\"cateImage\" />"
		+"	<result column=\"cate_sort\" jdbcType=\"VARCHAR\" property=\"cateSort\" />"
		+"	<result column=\"key_word\" jdbcType=\"VARCHAR\" property=\"keyWord\" />"
		+"	<result column=\"cate_desc\" jdbcType=\"VARCHAR\" property=\"cateDesc\" />"
		+"	<result column=\"del\" jdbcType=\"CHAR\" property=\"del\" />"
	+"	</resultMap>"
	+"	<sql id=\"Base_Column_List\">"
		+"id,create_date,modify_date,type_id,quantity_unit,navigation_Bar,is_show,sort_manage,goods_num,cate_image,cate_sort,key_word,cate_desc,del"
	+"	</sql>"
	+"	<select id=\"selectById\" parameterType=\"String\" resultMap=\"BaseResultMap\">"
		+"	select "
		+"	<include refid=\"Base_Column_List\" />"
		+"	from t_goods_type_detail"
		+"	where id = #{id,jdbcType=VARCHAR}"
	+"	</select>"
	+"	<delete id=\"deleteById\" parameterType=\"String\">"
		+"	delete from t_goods_type_detail"
		+"	where id = #{id,jdbcType=VARCHAR}"
	+"	</delete>"
	+"	<insert id=\"insert\" keyColumn=\"id\" keyProperty=\"id\" parameterType=\"cn.sunline.demo.entity.TGoodsTypeDetail\" useGeneratedKeys=\"true\">"
		+"	insert into t_goods_type_detail"
		+"	<trim prefix=\"(\" suffix=\")\" suffixOverrides=\",\">"
			+"<if test=\"id != null\">"
				+"id,"
			+"</if>"
			+"<if test=\"createDate != null\">"
				+"create_date,"
			+"</if>"
			+"<if test=\"modifyDate != null\">"
				+"modify_date,"
			+"</if>"
			+"<if test=\"typeId != null\">"
				+"type_id,"
			+"</if>"
			+"<if test=\"quantityUnit != null\">"
				+"quantity_unit,"
			+"</if>"
			+"<if test=\"navigationBar != null\">"
				+"navigation_Bar,"
			+"</if>"
			+"<if test=\"isShow != null\">"
				+"is_show,"
			+"</if>"
			+"<if test=\"sortManage != null\">"
				+"sort_manage,"
			+"</if>"
			+"<if test=\"goodsNum != null\">"
				+"goods_num,"
			+"</if>"
			+"<if test=\"cateImage != null\">"
				+"cate_image,"
			+"</if>"
			+"<if test=\"cateSort != null\">"
				+"cate_sort,"
			+"</if>"
			+"<if test=\"keyWord != null\">"
				+"key_word,"
			+"</if>"
			+"<if test=\"cateDesc != null\">"
				+"cate_desc,"
			+"</if>"
			+"<if test=\"del != null\">"
				+"del,"
			+"</if>"
		+"	</trim>"
		+"	<trim prefix=\"values (\" suffix=\")\" suffixOverrides=\",\">"
			+"<if test=\"id != null\">"
				+"#{id,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"createDate != null\">"
				+"#{createDate,jdbcType=TIMESTAMP},"
			+"</if>"
			+"<if test=\"modifyDate != null\">"
				+"#{modifyDate,jdbcType=TIMESTAMP},"
			+"</if>"
			+"<if test=\"typeId != null\">"
				+"#{typeId,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"quantityUnit != null\">"
				+"#{quantityUnit,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"navigationBar != null\">"
				+"#{navigationBar,jdbcType=CHAR},"
			+"</if>"
			+"<if test=\"isShow != null\">"
				+"#{isShow,jdbcType=CHAR},"
			+"</if>"
			+"<if test=\"sortManage != null\">"
				+"#{sortManage,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"goodsNum != null\">"
				+"#{goodsNum,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"cateImage != null\">"
				+"#{cateImage,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"cateSort != null\">"
				+"#{cateSort,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"keyWord != null\">"
				+"#{keyWord,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"cateDesc != null\">"
				+"#{cateDesc,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"del != null\">"
				+"#{del,jdbcType=CHAR},"
			+"</if>"
		+"	</trim>"
	+"	</insert>"
	+"	<update id=\"updateById\" parameterType=\"cn.sunline.demo.entity.TGoodsTypeDetail\">"
		+"	update t_goods_type_detail"
		+"	<set>"
		+"	<if test=\"createDate != null\">"
			+"create_date = #{createDate,jdbcType=TIMESTAMP},"
		+"	</if>"
		+"	<if test=\"modifyDate != null\">"
			+"modify_date = #{modifyDate,jdbcType=TIMESTAMP},"
		+"	</if>"
		+"	<if test=\"typeId != null\">"
			+"type_id = #{typeId,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"quantityUnit != null\">"
			+"quantity_unit = #{quantityUnit,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"navigationBar != null\">"
			+"navigation_Bar = #{navigationBar,jdbcType=CHAR},"
		+"	</if>"
		+"	<if test=\"isShow != null\">"
			+"is_show = #{isShow,jdbcType=CHAR},"
		+"	</if>"
		+"	<if test=\"sortManage != null\">"
			+"sort_manage = #{sortManage,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"goodsNum != null\">"
			+"goods_num = #{goodsNum,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"cateImage != null\">"
			+"cate_image = #{cateImage,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"cateSort != null\">"
			+"cate_sort = #{cateSort,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"keyWord != null\">"
			+"key_word = #{keyWord,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"cateDesc != null\">"
			+"cate_desc = #{cateDesc,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"del != null\">"
			+"del = #{del,jdbcType=CHAR},"
		+"	</if>"
		+"	</set>"
		+"	where id = #{id,jdbcType=VARCHAR}"
	+"	</update>";
	}
	public static String getTMenuMapper() {

return	"<resultMap id=\"BaseResultMap\" type=\"cn.sunline.demo.entity.TMenu\">"
		+"	<id column=\"id\" jdbcType=\"VARCHAR\" property=\"id\" />"
		+"	<result column=\"create_date\" jdbcType=\"TIMESTAMP\" property=\"createDate\" />"
		+"	<result column=\"modify_date\" jdbcType=\"TIMESTAMP\" property=\"modifyDate\" />"
		+"	<result column=\"menu_id\" jdbcType=\"VARCHAR\" property=\"menuId\" />"
		+"	<result column=\"menu_name\" jdbcType=\"VARCHAR\" property=\"menuName\" />"
		+"	<result column=\"menu_par_id\" jdbcType=\"VARCHAR\" property=\"menuParId\" />"
		+"	<result column=\"m_state\" jdbcType=\"CHAR\" property=\"mState\" />"
		+"	<result column=\"m_tourl\" jdbcType=\"VARCHAR\" property=\"mTourl\" />"
		+"	<result column=\"del\" jdbcType=\"CHAR\" property=\"del\" />"
	+"	</resultMap>"
	+"	<sql id=\"Base_Column_List\">"
		+"id,create_date,modify_date,menu_id,menu_name,menu_par_id,m_state,m_tourl,del"
	+"	</sql>"
	+"	<select id=\"selectById\" parameterType=\"String\" resultMap=\"BaseResultMap\">"
		+"	select "
		+"	<include refid=\"Base_Column_List\" />"
		+"	from t_menu"
		+"	where id = #{id,jdbcType=VARCHAR}"
	+"	</select>"
	+"	<delete id=\"deleteById\" parameterType=\"String\">"
		+"	delete from t_menu"
		+"	where id = #{id,jdbcType=VARCHAR}"
	+"	</delete>"
	+"	<insert id=\"insert\" keyColumn=\"id\" keyProperty=\"id\" parameterType=\"cn.sunline.demo.entity.TMenu\" useGeneratedKeys=\"true\">"
		+"	insert into t_menu"
		+"	<trim prefix=\"(\" suffix=\")\" suffixOverrides=\",\">"
			+"<if test=\"id != null\">"
				+"id,"
			+"</if>"
			+"<if test=\"createDate != null\">"
				+"create_date,"
			+"</if>"
			+"<if test=\"modifyDate != null\">"
				+"modify_date,"
			+"</if>"
			+"<if test=\"menuId != null\">"
				+"menu_id,"
			+"</if>"
			+"<if test=\"menuName != null\">"
				+"menu_name,"
			+"</if>"
			+"<if test=\"menuParId != null\">"
				+"menu_par_id,"
			+"</if>"
			+"<if test=\"mState != null\">"
				+"m_state,"
			+"</if>"
			+"<if test=\"mTourl != null\">"
				+"m_tourl,"
			+"</if>"
			+"<if test=\"del != null\">"
				+"del,"
			+"</if>"
		+"	</trim>"
		+"	<trim prefix=\"values (\" suffix=\")\" suffixOverrides=\",\">"
			+"<if test=\"id != null\">"
				+"#{id,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"createDate != null\">"
				+"#{createDate,jdbcType=TIMESTAMP},"
			+"</if>"
			+"<if test=\"modifyDate != null\">"
				+"#{modifyDate,jdbcType=TIMESTAMP},"
			+"</if>"
			+"<if test=\"menuId != null\">"
				+"#{menuId,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"menuName != null\">"
				+"#{menuName,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"menuParId != null\">"
				+"#{menuParId,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"mState != null\">"
				+"#{mState,jdbcType=CHAR},"
			+"</if>"
			+"<if test=\"mTourl != null\">"
				+"#{mTourl,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"del != null\">"
				+"#{del,jdbcType=CHAR},"
			+"</if>"
		+"	</trim>"
	+"	</insert>"
	+"	<update id=\"updateById\" parameterType=\"cn.sunline.demo.entity.TMenu\">"
		+"	update t_menu"
		+"	<set>"
		+"	<if test=\"createDate != null\">"
			+"create_date = #{createDate,jdbcType=TIMESTAMP},"
		+"	</if>"
		+"	<if test=\"modifyDate != null\">"
			+"modify_date = #{modifyDate,jdbcType=TIMESTAMP},"
		+"	</if>"
		+"	<if test=\"menuId != null\">"
			+"menu_id = #{menuId,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"menuName != null\">"
			+"menu_name = #{menuName,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"menuParId != null\">"
			+"menu_par_id = #{menuParId,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"mState != null\">"
			+"m_state = #{mState,jdbcType=CHAR},"
		+"	</if>"
		+"	<if test=\"mTourl != null\">"
			+"m_tourl = #{mTourl,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"del != null\">"
			+"del = #{del,jdbcType=CHAR},"
		+"	</if>"
		+"	</set>"
		+"	where id = #{id,jdbcType=VARCHAR}"
	+"	</update>";
	}
	public static String getTOrderMapper() {

return	"<resultMap id=\"BaseResultMap\" type=\"cn.sunline.demo.entity.TOrder\">"
		+"	<id column=\"id\" jdbcType=\"VARCHAR\" property=\"id\" />"
		+"	<result column=\"create_date\" jdbcType=\"TIMESTAMP\" property=\"createDate\" />"
		+"	<result column=\"modify_date\" jdbcType=\"TIMESTAMP\" property=\"modifyDate\" />"
		+"	<result column=\"order_id\" jdbcType=\"VARCHAR\" property=\"orderId\" />"
		+"	<result column=\"good_id\" jdbcType=\"VARCHAR\" property=\"goodId\" />"
		+"	<result column=\"user_id\" jdbcType=\"BIGINT\" property=\"userId\" />"
		+"	<result column=\"date_of_oeder\" jdbcType=\"TIMESTAMP\" property=\"dateOfOeder\" />"
		+"	<result column=\"order_state\" jdbcType=\"CHAR\" property=\"orderState\" />"
		+"	<result column=\"del\" jdbcType=\"CHAR\" property=\"del\" />"
	+"	</resultMap>"
	+"	<sql id=\"Base_Column_List\">"
		+"id,create_date,modify_date,order_id,good_id,user_id,date_of_oeder,order_state,del"
	+"	</sql>"
	+"	<select id=\"selectById\" parameterType=\"String\" resultMap=\"BaseResultMap\">"
		+"	select "
		+"	<include refid=\"Base_Column_List\" />"
		+"	from t_order"
		+"	where id = #{id,jdbcType=VARCHAR}"
	+"	</select>"
	+"	<delete id=\"deleteById\" parameterType=\"String\">"
		+"	delete from t_order"
		+"	where id = #{id,jdbcType=VARCHAR}"
	+"	</delete>"
	+"	<insert id=\"insert\" keyColumn=\"id\" keyProperty=\"id\" parameterType=\"cn.sunline.demo.entity.TOrder\" useGeneratedKeys=\"true\">"
		+"	insert into t_order"
		+"	<trim prefix=\"(\" suffix=\")\" suffixOverrides=\",\">"
			+"<if test=\"id != null\">"
				+"id,"
			+"</if>"
			+"<if test=\"createDate != null\">"
				+"create_date,"
			+"</if>"
			+"<if test=\"modifyDate != null\">"
				+"modify_date,"
			+"</if>"
			+"<if test=\"orderId != null\">"
				+"order_id,"
			+"</if>"
			+"<if test=\"goodId != null\">"
				+"good_id,"
			+"</if>"
			+"<if test=\"userId != null\">"
				+"user_id,"
			+"</if>"
			+"<if test=\"dateOfOeder != null\">"
				+"date_of_oeder,"
			+"</if>"
			+"<if test=\"orderState != null\">"
				+"order_state,"
			+"</if>"
			+"<if test=\"del != null\">"
				+"del,"
			+"</if>"
		+"	</trim>"
		+"	<trim prefix=\"values (\" suffix=\")\" suffixOverrides=\",\">"
			+"<if test=\"id != null\">"
				+"#{id,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"createDate != null\">"
				+"#{createDate,jdbcType=TIMESTAMP},"
			+"</if>"
			+"<if test=\"modifyDate != null\">"
				+"#{modifyDate,jdbcType=TIMESTAMP},"
			+"</if>"
			+"<if test=\"orderId != null\">"
				+"#{orderId,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"goodId != null\">"
				+"#{goodId,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"userId != null\">"
				+"#{userId,jdbcType=BIGINT},"
			+"</if>"
			+"<if test=\"dateOfOeder != null\">"
				+"#{dateOfOeder,jdbcType=TIMESTAMP},"
			+"</if>"
			+"<if test=\"orderState != null\">"
				+"#{orderState,jdbcType=CHAR},"
			+"</if>"
			+"<if test=\"del != null\">"
				+"#{del,jdbcType=CHAR},"
			+"</if>"
		+"	</trim>"
	+"	</insert>"
	+"	<update id=\"updateById\" parameterType=\"cn.sunline.demo.entity.TOrder\">"
		+"	update t_order"
		+"	<set>"
		+"	<if test=\"createDate != null\">"
			+"create_date = #{createDate,jdbcType=TIMESTAMP},"
		+"	</if>"
		+"	<if test=\"modifyDate != null\">"
			+"modify_date = #{modifyDate,jdbcType=TIMESTAMP},"
		+"	</if>"
		+"	<if test=\"orderId != null\">"
			+"order_id = #{orderId,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"goodId != null\">"
			+"good_id = #{goodId,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"userId != null\">"
			+"user_id = #{userId,jdbcType=BIGINT},"
		+"	</if>"
		+"	<if test=\"dateOfOeder != null\">"
			+"date_of_oeder = #{dateOfOeder,jdbcType=TIMESTAMP},"
		+"	</if>"
		+"	<if test=\"orderState != null\">"
			+"order_state = #{orderState,jdbcType=CHAR},"
		+"	</if>"
		+"	<if test=\"del != null\">"
			+"del = #{del,jdbcType=CHAR},"
		+"	</if>"
		+"	</set>"
		+"	where id = #{id,jdbcType=VARCHAR}"
	+"	</update>";
	}
	public static String getTOtherSysCodeMapper() {

return	"<resultMap id=\"BaseResultMap\" type=\"cn.sunline.demo.entity.TOtherSysCode\">"
		+"	<id column=\"id\" jdbcType=\"VARCHAR\" property=\"id\" />"
		+"	<result column=\"create_date\" jdbcType=\"TIMESTAMP\" property=\"createDate\" />"
		+"	<result column=\"modify_date\" jdbcType=\"TIMESTAMP\" property=\"modifyDate\" />"
		+"	<result column=\"sys_n\" jdbcType=\"CHAR\" property=\"sysN\" />"
		+"	<result column=\"trans_code\" jdbcType=\"VARCHAR\" property=\"transCode\" />"
		+"	<result column=\"erorcd\" jdbcType=\"VARCHAR\" property=\"erorcd\" />"
		+"	<result column=\"erortx\" jdbcType=\"VARCHAR\" property=\"erortx\" />"
		+"	<result column=\"data_language\" jdbcType=\"CHAR\" property=\"dataLanguage\" />"
		+"	<result column=\"t_status\" jdbcType=\"CHAR\" property=\"tStatus\" />"
		+"	<result column=\"del\" jdbcType=\"TINYINT\" property=\"del\" />"
	+"	</resultMap>"
	+"	<sql id=\"Base_Column_List\">"
		+"id,create_date,modify_date,sys_n,trans_code,erorcd,erortx,data_language,t_status,del"
	+"	</sql>"
	+"	<select id=\"selectById\" parameterType=\"String\" resultMap=\"BaseResultMap\">"
		+"	select "
		+"	<include refid=\"Base_Column_List\" />"
		+"	from t_other_sys_code"
		+"	where id = #{id,jdbcType=VARCHAR}"
	+"	</select>"
	+"	<delete id=\"deleteById\" parameterType=\"String\">"
		+"	delete from t_other_sys_code"
		+"	where id = #{id,jdbcType=VARCHAR}"
	+"	</delete>"
	+"	<insert id=\"insert\" keyColumn=\"id\" keyProperty=\"id\" parameterType=\"cn.sunline.demo.entity.TOtherSysCode\" useGeneratedKeys=\"true\">"
		+"	insert into t_other_sys_code"
		+"	<trim prefix=\"(\" suffix=\")\" suffixOverrides=\",\">"
			+"<if test=\"id != null\">"
				+"id,"
			+"</if>"
			+"<if test=\"createDate != null\">"
				+"create_date,"
			+"</if>"
			+"<if test=\"modifyDate != null\">"
				+"modify_date,"
			+"</if>"
			+"<if test=\"sysN != null\">"
				+"sys_n,"
			+"</if>"
			+"<if test=\"transCode != null\">"
				+"trans_code,"
			+"</if>"
			+"<if test=\"erorcd != null\">"
				+"erorcd,"
			+"</if>"
			+"<if test=\"erortx != null\">"
				+"erortx,"
			+"</if>"
			+"<if test=\"dataLanguage != null\">"
				+"data_language,"
			+"</if>"
			+"<if test=\"tStatus != null\">"
				+"t_status,"
			+"</if>"
			+"<if test=\"del != null\">"
				+"del,"
			+"</if>"
		+"	</trim>"
		+"	<trim prefix=\"values (\" suffix=\")\" suffixOverrides=\",\">"
			+"<if test=\"id != null\">"
				+"#{id,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"createDate != null\">"
				+"#{createDate,jdbcType=TIMESTAMP},"
			+"</if>"
			+"<if test=\"modifyDate != null\">"
				+"#{modifyDate,jdbcType=TIMESTAMP},"
			+"</if>"
			+"<if test=\"sysN != null\">"
				+"#{sysN,jdbcType=CHAR},"
			+"</if>"
			+"<if test=\"transCode != null\">"
				+"#{transCode,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"erorcd != null\">"
				+"#{erorcd,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"erortx != null\">"
				+"#{erortx,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"dataLanguage != null\">"
				+"#{dataLanguage,jdbcType=CHAR},"
			+"</if>"
			+"<if test=\"tStatus != null\">"
				+"#{tStatus,jdbcType=CHAR},"
			+"</if>"
			+"<if test=\"del != null\">"
				+"#{del,jdbcType=TINYINT},"
			+"</if>"
		+"	</trim>"
	+"	</insert>"
	+"	<update id=\"updateById\" parameterType=\"cn.sunline.demo.entity.TOtherSysCode\">"
		+"	update t_other_sys_code"
		+"	<set>"
		+"	<if test=\"createDate != null\">"
			+"create_date = #{createDate,jdbcType=TIMESTAMP},"
		+"	</if>"
		+"	<if test=\"modifyDate != null\">"
			+"modify_date = #{modifyDate,jdbcType=TIMESTAMP},"
		+"	</if>"
		+"	<if test=\"sysN != null\">"
			+"sys_n = #{sysN,jdbcType=CHAR},"
		+"	</if>"
		+"	<if test=\"transCode != null\">"
			+"trans_code = #{transCode,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"erorcd != null\">"
			+"erorcd = #{erorcd,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"erortx != null\">"
			+"erortx = #{erortx,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"dataLanguage != null\">"
			+"data_language = #{dataLanguage,jdbcType=CHAR},"
		+"	</if>"
		+"	<if test=\"tStatus != null\">"
			+"t_status = #{tStatus,jdbcType=CHAR},"
		+"	</if>"
		+"	<if test=\"del != null\">"
			+"del = #{del,jdbcType=TINYINT},"
		+"	</if>"
		+"	</set>"
		+"	where id = #{id,jdbcType=VARCHAR}"
	+"	</update>";
	}
	public static String getTRoleMapper() {

return	"<resultMap id=\"BaseResultMap\" type=\"cn.sunline.demo.entity.TRole\">"
		+"	<id column=\"id\" jdbcType=\"VARCHAR\" property=\"id\" />"
		+"	<result column=\"create_date\" jdbcType=\"TIMESTAMP\" property=\"createDate\" />"
		+"	<result column=\"modify_date\" jdbcType=\"TIMESTAMP\" property=\"modifyDate\" />"
		+"	<result column=\"role_id\" jdbcType=\"BIGINT\" property=\"roleId\" />"
		+"	<result column=\"role_name\" jdbcType=\"VARCHAR\" property=\"roleName\" />"
		+"	<result column=\"del\" jdbcType=\"CHAR\" property=\"del\" />"
	+"	</resultMap>"
	+"	<sql id=\"Base_Column_List\">"
		+"id,create_date,modify_date,role_id,role_name,del"
	+"	</sql>"
	+"	<select id=\"selectById\" parameterType=\"String\" resultMap=\"BaseResultMap\">"
		+"	select "
		+"	<include refid=\"Base_Column_List\" />"
		+"	from t_role"
		+"	where id = #{id,jdbcType=VARCHAR}"
	+"	</select>"
	+"	<delete id=\"deleteById\" parameterType=\"String\">"
		+"	delete from t_role"
		+"	where id = #{id,jdbcType=VARCHAR}"
	+"	</delete>"
	+"	<insert id=\"insert\" keyColumn=\"id\" keyProperty=\"id\" parameterType=\"cn.sunline.demo.entity.TRole\" useGeneratedKeys=\"true\">"
		+"	insert into t_role"
		+"	<trim prefix=\"(\" suffix=\")\" suffixOverrides=\",\">"
			+"<if test=\"id != null\">"
				+"id,"
			+"</if>"
			+"<if test=\"createDate != null\">"
				+"create_date,"
			+"</if>"
			+"<if test=\"modifyDate != null\">"
				+"modify_date,"
			+"</if>"
			+"<if test=\"roleId != null\">"
				+"role_id,"
			+"</if>"
			+"<if test=\"roleName != null\">"
				+"role_name,"
			+"</if>"
			+"<if test=\"del != null\">"
				+"del,"
			+"</if>"
		+"	</trim>"
		+"	<trim prefix=\"values (\" suffix=\")\" suffixOverrides=\",\">"
			+"<if test=\"id != null\">"
				+"#{id,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"createDate != null\">"
				+"#{createDate,jdbcType=TIMESTAMP},"
			+"</if>"
			+"<if test=\"modifyDate != null\">"
				+"#{modifyDate,jdbcType=TIMESTAMP},"
			+"</if>"
			+"<if test=\"roleId != null\">"
				+"#{roleId,jdbcType=BIGINT},"
			+"</if>"
			+"<if test=\"roleName != null\">"
				+"#{roleName,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"del != null\">"
				+"#{del,jdbcType=CHAR},"
			+"</if>"
		+"	</trim>"
	+"	</insert>"
	+"	<update id=\"updateById\" parameterType=\"cn.sunline.demo.entity.TRole\">"
		+"	update t_role"
		+"	<set>"
		+"	<if test=\"createDate != null\">"
			+"create_date = #{createDate,jdbcType=TIMESTAMP},"
		+"	</if>"
		+"	<if test=\"modifyDate != null\">"
			+"modify_date = #{modifyDate,jdbcType=TIMESTAMP},"
		+"	</if>"
		+"	<if test=\"roleId != null\">"
			+"role_id = #{roleId,jdbcType=BIGINT},"
		+"	</if>"
		+"	<if test=\"roleName != null\">"
			+"role_name = #{roleName,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"del != null\">"
			+"del = #{del,jdbcType=CHAR},"
		+"	</if>"
		+"	</set>"
		+"	where id = #{id,jdbcType=VARCHAR}"
	+"	</update>";
	}
	public static String getTShoppingcartMapper() {

return	"<resultMap id=\"BaseResultMap\" type=\"cn.sunline.demo.entity.TShoppingcart\">"
		+"	<id column=\"id\" jdbcType=\"VARCHAR\" property=\"id\" />"
		+"	<result column=\"create_date\" jdbcType=\"TIMESTAMP\" property=\"createDate\" />"
		+"	<result column=\"modify_date\" jdbcType=\"TIMESTAMP\" property=\"modifyDate\" />"
		+"	<result column=\"shoppcart_id\" jdbcType=\"VARCHAR\" property=\"shoppcartId\" />"
		+"	<result column=\"good_id\" jdbcType=\"VARCHAR\" property=\"goodId\" />"
		+"	<result column=\"good_name\" jdbcType=\"VARCHAR\" property=\"goodName\" />"
		+"	<result column=\"good_desc\" jdbcType=\"VARCHAR\" property=\"goodDesc\" />"
		+"	<result column=\"good_price\" jdbcType=\"VARCHAR\" property=\"goodPrice\" />"
		+"	<result column=\"good_type\" jdbcType=\"VARCHAR\" property=\"goodType\" />"
		+"	<result column=\"user_id\" jdbcType=\"BIGINT\" property=\"userId\" />"
		+"	<result column=\"del\" jdbcType=\"CHAR\" property=\"del\" />"
	+"	</resultMap>"
	+"	<sql id=\"Base_Column_List\">"
		+"id,create_date,modify_date,shoppcart_id,good_id,good_name,good_desc,good_price,good_type,user_id,del"
	+"	</sql>"
	+"	<select id=\"selectById\" parameterType=\"String\" resultMap=\"BaseResultMap\">"
		+"	select "
		+"	<include refid=\"Base_Column_List\" />"
		+"	from t_shoppingcart"
		+"	where id = #{id,jdbcType=VARCHAR}"
	+"	</select>"
	+"	<delete id=\"deleteById\" parameterType=\"String\">"
		+"	delete from t_shoppingcart"
		+"	where id = #{id,jdbcType=VARCHAR}"
	+"	</delete>"
	+"	<insert id=\"insert\" keyColumn=\"id\" keyProperty=\"id\" parameterType=\"cn.sunline.demo.entity.TShoppingcart\" useGeneratedKeys=\"true\">"
		+"	insert into t_shoppingcart"
		+"	<trim prefix=\"(\" suffix=\")\" suffixOverrides=\",\">"
			+"<if test=\"id != null\">"
				+"id,"
			+"</if>"
			+"<if test=\"createDate != null\">"
				+"create_date,"
			+"</if>"
			+"<if test=\"modifyDate != null\">"
				+"modify_date,"
			+"</if>"
			+"<if test=\"shoppcartId != null\">"
				+"shoppcart_id,"
			+"</if>"
			+"<if test=\"goodId != null\">"
				+"good_id,"
			+"</if>"
			+"<if test=\"goodName != null\">"
				+"good_name,"
			+"</if>"
			+"<if test=\"goodDesc != null\">"
				+"good_desc,"
			+"</if>"
			+"<if test=\"goodPrice != null\">"
				+"good_price,"
			+"</if>"
			+"<if test=\"goodType != null\">"
				+"good_type,"
			+"</if>"
			+"<if test=\"userId != null\">"
				+"user_id,"
			+"</if>"
			+"<if test=\"del != null\">"
				+"del,"
			+"</if>"
		+"	</trim>"
		+"	<trim prefix=\"values (\" suffix=\")\" suffixOverrides=\",\">"
			+"<if test=\"id != null\">"
				+"#{id,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"createDate != null\">"
				+"#{createDate,jdbcType=TIMESTAMP},"
			+"</if>"
			+"<if test=\"modifyDate != null\">"
				+"#{modifyDate,jdbcType=TIMESTAMP},"
			+"</if>"
			+"<if test=\"shoppcartId != null\">"
				+"#{shoppcartId,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"goodId != null\">"
				+"#{goodId,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"goodName != null\">"
				+"#{goodName,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"goodDesc != null\">"
				+"#{goodDesc,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"goodPrice != null\">"
				+"#{goodPrice,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"goodType != null\">"
				+"#{goodType,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"userId != null\">"
				+"#{userId,jdbcType=BIGINT},"
			+"</if>"
			+"<if test=\"del != null\">"
				+"#{del,jdbcType=CHAR},"
			+"</if>"
		+"	</trim>"
	+"	</insert>"
	+"	<update id=\"updateById\" parameterType=\"cn.sunline.demo.entity.TShoppingcart\">"
		+"	update t_shoppingcart"
		+"	<set>"
		+"	<if test=\"createDate != null\">"
			+"create_date = #{createDate,jdbcType=TIMESTAMP},"
		+"	</if>"
		+"	<if test=\"modifyDate != null\">"
			+"modify_date = #{modifyDate,jdbcType=TIMESTAMP},"
		+"	</if>"
		+"	<if test=\"shoppcartId != null\">"
			+"shoppcart_id = #{shoppcartId,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"goodId != null\">"
			+"good_id = #{goodId,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"goodName != null\">"
			+"good_name = #{goodName,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"goodDesc != null\">"
			+"good_desc = #{goodDesc,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"goodPrice != null\">"
			+"good_price = #{goodPrice,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"goodType != null\">"
			+"good_type = #{goodType,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"userId != null\">"
			+"user_id = #{userId,jdbcType=BIGINT},"
		+"	</if>"
		+"	<if test=\"del != null\">"
			+"del = #{del,jdbcType=CHAR},"
		+"	</if>"
		+"	</set>"
		+"	where id = #{id,jdbcType=VARCHAR}"
	+"	</update>";
	}
	public static String getTUserRoleMapper() {

return	"<resultMap id=\"BaseResultMap\" type=\"cn.sunline.demo.entity.TUserRole\">"
		+"	<id column=\"id\" jdbcType=\"VARCHAR\" property=\"id\" />"
		+"	<result column=\"create_date\" jdbcType=\"TIMESTAMP\" property=\"createDate\" />"
		+"	<result column=\"modify_date\" jdbcType=\"TIMESTAMP\" property=\"modifyDate\" />"
		+"	<result column=\"user_id\" jdbcType=\"BIGINT\" property=\"userId\" />"
		+"	<result column=\"role_id\" jdbcType=\"BIGINT\" property=\"roleId\" />"
		+"	<result column=\"del\" jdbcType=\"CHAR\" property=\"del\" />"
	+"	</resultMap>"
	+"	<sql id=\"Base_Column_List\">"
		+"id,create_date,modify_date,user_id,role_id,del"
	+"	</sql>"
	+"	<select id=\"selectById\" parameterType=\"String\" resultMap=\"BaseResultMap\">"
		+"	select "
		+"	<include refid=\"Base_Column_List\" />"
		+"	from t_user_role"
		+"	where id = #{id,jdbcType=VARCHAR}"
	+"	</select>"
	+"	<delete id=\"deleteById\" parameterType=\"String\">"
		+"	delete from t_user_role"
		+"	where id = #{id,jdbcType=VARCHAR}"
	+"	</delete>"
	+"	<insert id=\"insert\" keyColumn=\"id\" keyProperty=\"id\" parameterType=\"cn.sunline.demo.entity.TUserRole\" useGeneratedKeys=\"true\">"
		+"	insert into t_user_role"
		+"	<trim prefix=\"(\" suffix=\")\" suffixOverrides=\",\">"
			+"<if test=\"id != null\">"
				+"id,"
			+"</if>"
			+"<if test=\"createDate != null\">"
				+"create_date,"
			+"</if>"
			+"<if test=\"modifyDate != null\">"
				+"modify_date,"
			+"</if>"
			+"<if test=\"userId != null\">"
				+"user_id,"
			+"</if>"
			+"<if test=\"roleId != null\">"
				+"role_id,"
			+"</if>"
			+"<if test=\"del != null\">"
				+"del,"
			+"</if>"
		+"	</trim>"
		+"	<trim prefix=\"values (\" suffix=\")\" suffixOverrides=\",\">"
			+"<if test=\"id != null\">"
				+"#{id,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"createDate != null\">"
				+"#{createDate,jdbcType=TIMESTAMP},"
			+"</if>"
			+"<if test=\"modifyDate != null\">"
				+"#{modifyDate,jdbcType=TIMESTAMP},"
			+"</if>"
			+"<if test=\"userId != null\">"
				+"#{userId,jdbcType=BIGINT},"
			+"</if>"
			+"<if test=\"roleId != null\">"
				+"#{roleId,jdbcType=BIGINT},"
			+"</if>"
			+"<if test=\"del != null\">"
				+"#{del,jdbcType=CHAR},"
			+"</if>"
		+"	</trim>"
	+"	</insert>"
	+"	<update id=\"updateById\" parameterType=\"cn.sunline.demo.entity.TUserRole\">"
		+"	update t_user_role"
		+"	<set>"
		+"	<if test=\"createDate != null\">"
			+"create_date = #{createDate,jdbcType=TIMESTAMP},"
		+"	</if>"
		+"	<if test=\"modifyDate != null\">"
			+"modify_date = #{modifyDate,jdbcType=TIMESTAMP},"
		+"	</if>"
		+"	<if test=\"userId != null\">"
			+"user_id = #{userId,jdbcType=BIGINT},"
		+"	</if>"
		+"	<if test=\"roleId != null\">"
			+"role_id = #{roleId,jdbcType=BIGINT},"
		+"	</if>"
		+"	<if test=\"del != null\">"
			+"del = #{del,jdbcType=CHAR},"
		+"	</if>"
		+"	</set>"
		+"	where id = #{id,jdbcType=VARCHAR}"
	+"	</update>";
	}
	public static String getTUsersMapper() {

return	"<resultMap id=\"BaseResultMap\" type=\"cn.sunline.demo.entity.TUsers\">"
		+"	<id column=\"id\" jdbcType=\"VARCHAR\" property=\"id\" />"
		+"	<result column=\"create_date\" jdbcType=\"TIMESTAMP\" property=\"createDate\" />"
		+"	<result column=\"modify_date\" jdbcType=\"TIMESTAMP\" property=\"modifyDate\" />"
		+"	<result column=\"user_name\" jdbcType=\"VARCHAR\" property=\"userName\" />"
		+"	<result column=\"nick_name\" jdbcType=\"VARCHAR\" property=\"nickName\" />"
		+"	<result column=\"user_id\" jdbcType=\"BIGINT\" property=\"userId\" />"
		+"	<result column=\"mobile\" jdbcType=\"VARCHAR\" property=\"mobile\" />"
		+"	<result column=\"email\" jdbcType=\"VARCHAR\" property=\"email\" />"
		+"	<result column=\"date_of_birth\" jdbcType=\"TIMESTAMP\" property=\"dateOfBirth\" />"
		+"	<result column=\"gender\" jdbcType=\"CHAR\" property=\"gender\" />"
		+"	<result column=\"address\" jdbcType=\"VARCHAR\" property=\"address\" />"
		+"	<result column=\"mobile_phone\" jdbcType=\"VARCHAR\" property=\"mobilePhone\" />"
		+"	<result column=\"status\" jdbcType=\"CHAR\" property=\"status\" />"
		+"	<result column=\"del\" jdbcType=\"CHAR\" property=\"del\" />"
		+"	<result column=\"login_password\" jdbcType=\"VARCHAR\" property=\"loginPassword\" />"
	+"	</resultMap>"
	+"	<sql id=\"Base_Column_List\">"
		+"id,create_date,modify_date,user_name,nick_name,user_id,mobile,email,date_of_birth,gender,address,mobile_phone,status,del,login_password"
	+"	</sql>"
	+"	<select id=\"selectById\" parameterType=\"String\" resultMap=\"BaseResultMap\">"
		+"	select "
		+"	<include refid=\"Base_Column_List\" />"
		+"	from t_users"
		+"	where id = #{id,jdbcType=VARCHAR}"
	+"	</select>"
	+"	<delete id=\"deleteById\" parameterType=\"String\">"
		+"	delete from t_users"
		+"	where id = #{id,jdbcType=VARCHAR}"
	+"	</delete>"
	+"	<insert id=\"insert\" keyColumn=\"id\" keyProperty=\"id\" parameterType=\"cn.sunline.demo.entity.TUsers\" useGeneratedKeys=\"true\">"
		+"	insert into t_users"
		+"	<trim prefix=\"(\" suffix=\")\" suffixOverrides=\",\">"
			+"<if test=\"id != null\">"
				+"id,"
			+"</if>"
			+"<if test=\"createDate != null\">"
				+"create_date,"
			+"</if>"
			+"<if test=\"modifyDate != null\">"
				+"modify_date,"
			+"</if>"
			+"<if test=\"userName != null\">"
				+"user_name,"
			+"</if>"
			+"<if test=\"nickName != null\">"
				+"nick_name,"
			+"</if>"
			+"<if test=\"userId != null\">"
				+"user_id,"
			+"</if>"
			+"<if test=\"mobile != null\">"
				+"mobile,"
			+"</if>"
			+"<if test=\"email != null\">"
				+"email,"
			+"</if>"
			+"<if test=\"dateOfBirth != null\">"
				+"date_of_birth,"
			+"</if>"
			+"<if test=\"gender != null\">"
				+"gender,"
			+"</if>"
			+"<if test=\"address != null\">"
				+"address,"
			+"</if>"
			+"<if test=\"mobilePhone != null\">"
				+"mobile_phone,"
			+"</if>"
			+"<if test=\"status != null\">"
				+"status,"
			+"</if>"
			+"<if test=\"del != null\">"
				+"del,"
			+"</if>"
			+"<if test=\"loginPassword != null\">"
				+"login_password,"
			+"</if>"
		+"	</trim>"
		+"	<trim prefix=\"values (\" suffix=\")\" suffixOverrides=\",\">"
			+"<if test=\"id != null\">"
				+"#{id,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"createDate != null\">"
				+"#{createDate,jdbcType=TIMESTAMP},"
			+"</if>"
			+"<if test=\"modifyDate != null\">"
				+"#{modifyDate,jdbcType=TIMESTAMP},"
			+"</if>"
			+"<if test=\"userName != null\">"
				+"#{userName,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"nickName != null\">"
				+"#{nickName,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"userId != null\">"
				+"#{userId,jdbcType=BIGINT},"
			+"</if>"
			+"<if test=\"mobile != null\">"
				+"#{mobile,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"email != null\">"
				+"#{email,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"dateOfBirth != null\">"
				+"#{dateOfBirth,jdbcType=TIMESTAMP},"
			+"</if>"
			+"<if test=\"gender != null\">"
				+"#{gender,jdbcType=CHAR},"
			+"</if>"
			+"<if test=\"address != null\">"
				+"#{address,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"mobilePhone != null\">"
				+"#{mobilePhone,jdbcType=VARCHAR},"
			+"</if>"
			+"<if test=\"status != null\">"
				+"#{status,jdbcType=CHAR},"
			+"</if>"
			+"<if test=\"del != null\">"
				+"#{del,jdbcType=CHAR},"
			+"</if>"
			+"<if test=\"loginPassword != null\">"
				+"#{loginPassword,jdbcType=VARCHAR},"
			+"</if>"
		+"	</trim>"
	+"	</insert>"
	+"	<update id=\"updateById\" parameterType=\"cn.sunline.demo.entity.TUsers\">"
		+"	update t_users"
		+"	<set>"
		+"	<if test=\"createDate != null\">"
			+"create_date = #{createDate,jdbcType=TIMESTAMP},"
		+"	</if>"
		+"	<if test=\"modifyDate != null\">"
			+"modify_date = #{modifyDate,jdbcType=TIMESTAMP},"
		+"	</if>"
		+"	<if test=\"userName != null\">"
			+"user_name = #{userName,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"nickName != null\">"
			+"nick_name = #{nickName,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"userId != null\">"
			+"user_id = #{userId,jdbcType=BIGINT},"
		+"	</if>"
		+"	<if test=\"mobile != null\">"
			+"mobile = #{mobile,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"email != null\">"
			+"email = #{email,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"dateOfBirth != null\">"
			+"date_of_birth = #{dateOfBirth,jdbcType=TIMESTAMP},"
		+"	</if>"
		+"	<if test=\"gender != null\">"
			+"gender = #{gender,jdbcType=CHAR},"
		+"	</if>"
		+"	<if test=\"address != null\">"
			+"address = #{address,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"mobilePhone != null\">"
			+"mobile_phone = #{mobilePhone,jdbcType=VARCHAR},"
		+"	</if>"
		+"	<if test=\"status != null\">"
			+"status = #{status,jdbcType=CHAR},"
		+"	</if>"
		+"	<if test=\"del != null\">"
			+"del = #{del,jdbcType=CHAR},"
		+"	</if>"
		+"	<if test=\"loginPassword != null\">"
			+"login_password = #{loginPassword,jdbcType=VARCHAR},"
		+"	</if>"
		+"	</set>"
		+"	where id = #{id,jdbcType=VARCHAR}"
	+"	</update>";
	}
}